In [2]:
!pip install numpy

     |████████████████████████████████| 15.4 MB 7.4 MB/s 
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


# Matrix addition

In [22]:
import numpy as np

#Matrix addition using Numpy

A = np.arange(6).reshape(2,-1)
B = np.arange(6,12).reshape(2,-1)
C = A+B

print(A,"+",B,"=",C)


[[0 1 2]
 [3 4 5]] + [[ 6  7  8]
 [ 9 10 11]] = [[ 6  8 10]
 [12 14 16]]


In [43]:
A = [[ i for i in range(1,3)]for j in range(2)]
B = [[ i for i in range(4,6)]for j in range(2)]
Zipped = zip(A,B)
index = [0,0]
if(len(A[0])!=len(B[0])):
    print("matrices cannot be multiplied!")
else:
    C = [[0 for i in range(len(A[0]))]for i in range(len(A))]
    for arr_a,arr_b in Zipped:
        Zipped_2 = zip(arr_a,arr_b)
        for a,b in Zipped_2:
            c = a*b
            C[index[0]][index[1]] = c
            index[1]+=1
            if index[1]==len(A[0]):
                index[0]+=1
                index[1]=0
    print(A,"*",B,"=",C)



[[1, 2], [1, 2]] * [[4, 5], [4, 5]] = [[4, 10, 0], [4, 10, 0]]
